version: '3.7'

services:
  db:
    build: db
    #command: --default-authentication-plugin=mysql_native_password
    environment:
      - MYSQL_ROOT_PASSWORD=password
    ports:
      - "33306:3306"
    volumes:
      - mysql_data:/var/lib/mysql
  adminer:
    image: adminer:latest
    environment:
      - ADMINER_DEFAULT_SERVER=db
      - ADMINER_DEFAULT_DB_NAME=chessdb
    ports:
      - 8081:8080

volumes:
  mysql_data: