version: '3.7'

services:
  db:
    build: bd
    command: --default-authentication-plugin=mysql_native_password
    env_file:
      - bd/bd.env
    ports:
      - 33306:3306
    volumes:
      - mysql_data:/var/lib/mysql
  adminer:
    image: adminer:latest
    env_file:
      - bd/bd.env
    ports:
      - 8081:8080

volumes:
  mysql_data: